name: Compile and Test

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm run test
